fix/doc pre-commit hook
* regex when generating README needs anchor at start
* add docs whats going on

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,20 +1,25 @@
 #!/bin/bash
 
+# stash to staged changes and run the testsuite
 git stash push -k
 
 if bash ./pipadoc.test 2>&1 | tee test.log ; then
+    # testsuite success, rebuild documentation
     lua pipadoc.lua -m asciidoc pipadoc.lua >pipadoc.txt &&
         git stash pop -q --index &&
         asciidoc -a toc pipadoc.txt &&
-        grep -v '// ' pipadoc.txt >README &&
+        grep -v '^// ' pipadoc.txt >README &&
         if git diff --numstat README |
                 { read a r f ; test $((a+r)) -gt 2; }; then
+            # stage docs only when anything more than 1 lines
+            # (generation date) changed
             git add README pipadoc.html
         fi
 
     ret=$?
 else
     ret=$?
+    echo "testsuite failed, abort commit" 1>&2
     git stash pop -q --index
 fi
 
